// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUname holds the string denoting the uname field in the database.
	FieldUname = "uname"

	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"

	// Table holds the table name of the user in the database.
	Table = "users"
	// DeviceTable is the table the holds the device relation/edge.
	DeviceTable = "devices"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUname,
}

var (
	// UnameValidator is a validator for the "Uname" field. It is called by the builders before save.
	UnameValidator func(string) error
)
